version: 2
jobs:
  test-job:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

      # Cache to enable faster future jobs
      - run: npm install --silent
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run: npm run test -- --progress=false --watch=false
  deploy-job:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: cd functions && npm install && cd ..
      - run: npm run prod
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2

  -test_and_deploy:
    jobs:
      - test-job
      - deploy-job:
          requires:
            - test-job
          filters:
            branches:
              only: master
